apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "meet-helm-chart.fullname" . }}
data:
    DB_HOST: {{ include "meet-helm-chart.fullname" . }}
    DJANGO_SETTINGS_MODULE: {{ .Values.configMap.django.DJANGO_SETTINGS_MODULE }}