apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wemeet.fullname" . }}
data:
  DB_HOST: {{ include "wemeet.db.fullname" . }}
  REDIS_HOST: {{ include "wemeet.redis.fullname" . }}
  DJANGO_SETTINGS_MODULE: {{ .Values.configMap.django.DJANGO_SETTINGS_MODULE }}