apiVersion: v1
kind: Service
metadata:
  name: {{ include "wemeet.fullname" . }}
  labels:
    {{- include "wemeet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.BeService.type }}
  ports:
    - port: {{ .Values.BeService.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wemeet.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wemeet.db.fullname" . }}
  labels:
    {{- include "wemeet.db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.DbService.type }}
  ports:
    - port: {{ .Values.DbService.port }}
      targetPort: {{ .Values.DbService.port }}
      protocol: TCP
  selector:
    {{- include "wemeet.db.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wemeet.redis.fullname" . }}
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.container.redisPort }}
      targetPort: {{ .Values.container.redisPort }}
  selector:
    {{- include "wemeet.selectorLabels" . | nindent 4 }}