version: '3'

services:
  web:
    depends_on:
      - db
    container_name: meet-app
    build:
      context: meet
      dockerfile: Dockerfile
    image: web
    volumes:
      - "meet_static:/var/www/html/static"
    command:
      - "/start"
    env_file:
      - ./.envs/local

  nginx:
    restart: always
    depends_on:
      - web
    container_name: meet-nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: lion-nginx
    ports:
      - "8888:80"
    volumes:
      - "meet_static:/var/www/html/static"
    env_file:
      - ./.envs/local

  db:
    image: postgres:13-alpine
    container_name: meet-db
    ports:
      - "5432:5432"
    volumes:
      - "meet_data:/var/lib/postgresql/data"

    env_file:
      - ./.envs/local

volumes:
  meet_data:
  meet_static:
