version: '3'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USRE: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wemeet
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: wemeet-web
    restart: always
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      ...:
