version: '3'

services:
  web:
    depends_on:
      - db
    container_name: meet-app
    build:
      context: meet
      dockerfile: Dockerfile
    image: web
    ports:
      - "8000:8000"
    volumes:
      - ./meet:/app
      - "meet_static:/var/www/html/static"
    command:
      - "/start"
    env_file:
      - ./.envs/local/django
      - ./.envs/local/db

  db:
    image: postgres:13-alpine
    container_name: meet-db
    ports:
      - "5432:5432"
    volumes:
      - "meet_data:/var/lib/postgresql/data"
    env_file:
      - ./.envs/local/db

volumes:
  meet_data:
  meet_static:
