version: '3'

services:
  web:
    depends_on:
      - db
      - celery-beat
    container_name: meet-app
    build:
      context: meet
      dockerfile: Dockerfile
    image: web
    ports:
      - "8000:8000"
    volumes:
      - ./meet:/app
      - "meet_static:/var/www/html/static"
    command:
      - "/start"
    env_file:
      - ./.envs/local/django
      - ./.envs/local/db

  db:
    image: postgres:13-alpine
    container_name: meet-db
    ports:
      - "5432:5432"
    volumes:
      - "meet_data:/var/lib/postgresql/data"
    env_file:
      - ./.envs/local/db

  celery-beat:
    image: web
    command: celery -A we-meet beat

  prometheus:
    container_name: meet-prom
    depends_on:
      - web
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./monitoring:/etc/prometheus
    command:
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - meet_grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123!@#

volumes:
  meet_data:
  meet_static:
  meet_grafana: