replicaCount: 1

image:
  repository: lion-cr01.kr.ncr.ntruss.com/we-meet
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: regcred
db:
  name: postgres
  tag: 13-alpine
nameOverride: ""
fullnameOverride: ""

BeService:
  type: LoadBalancer
  port: 80

DbService:
  type: ClusterIP
  port: 5432

container:
  bePort: 8000
  redisPort: 6379

configMap:
  django:
    DJANGO_SETTINGS_MODULE: "meet.settings.prod"

secret:
  db:
    POSTGRES_DB: postgres
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_PORT: "5432"
  django:
    DJANGO_SECRET_KEY: django-insecure-%1q)6f3d!g4i!siz-t9!)d@z=*5q_@5k%hz9jpt%2+$re+v+vk
    EMAIL_HOST_PASSWORD: "vqjy txpw ezrz lfkc"
