apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wemeet.fullname" . }}
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.secrets.django.DJANGO_SECRET_KEY | b64enc | quote }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wemeet.db.fullname" . }}
type: Opaque
data:
  {{- range $key, $val := .Values.secrets.db }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}