apiVersion: v1
kind: Service
metadata:
  name: {{ include "wemeet.fullname" . }}
  labels:
    {{- include "wemeet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.lb.type }}
  ports:
    - port: {{ .Values.services.lb.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "wemeet.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "wemeet.db.fullname" . }}
  labels:
    {{- include "wemeet.db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.db.type }}
  ports:
    - port: {{ .Values.services.db.port }}
      targetPort: {{ .Values.services.db.port }}
      protocol: TCP
  selector:
    {{- include "wemeet.db.selectorLabels" . | nindent 4 }}