apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stag-wemeet
  # namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wemeet
  endpoints:
    - port: http
      path: /metrics
      scheme: http
