name: CD

on:
  push:
    branches:
      - 'develop'
    tags:
      - "*.*.*"

env:
  IMAGE: ${{ vars.NCR_REGISTRY }}/we-meet
  IMAGE_TAG: ${{ vars.NCR_REGISTRY }}/we-meet:${{ github.run_number }}

jobs:

  build_and_push_image_to_registry:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: add test
        run: |
          docker-compose -f docker-compose-test.yml up --build -d
          docker-compose -f docker-compose-test.yml run web python manage.py test

      - name: Checkout code 
        uses: actions/checkout@v3 

      - name: Set up Docker buildx 
        uses: docker/setup-buildx-action@v2 

      - name: Login to NCR  
        uses: docker/login-action@v2   
        with:
          registry : ${{ vars.NCR_REGISTRY }}  
          username : ${{ secrets.NCR_ACCESS_KEY_ID }}  
          password : ${{ secrets.NCR_SECRET_KEY }}  

      - name: Get current timestamp
        if: startsWith(github.ref, 'refs/heads')
        id: timestamp    
        run: echo "timestamp=$(date '+%s')" >> "$GITHUB_ENV"   

      - name: Get version
        if: startsWith(github.ref, 'refs/tags')
        id: version   
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"  

      - name: Build and Push Image Tagged Timestamp   
        if: startsWith(github.ref, 'refs/heads')   
        uses: docker/build-push-action@v4     
        with:
          context: meet     
          tags: ${{ env.IMAGE }}:${{ github.run_number }},"${{ env.IMAGE }}:${{ steps.timestamp.outputs.timestamp }}"
          push: true  
      
      - name: Build and Push Image Tagged Version   
        if: startswith(github.ref, 'refs/tags')   
        uses: docker/build-push-action@v4     
        with:
          context: meet     
          tags: ${{ env.IMAGE }}:${{ github.run_number }},"${{ env.IMAGE }}:${{ steps.version.outputs.VERSION }}"
          push: true  
      