name: CD

on:
    push:
        branches:
            - 'develop'
        tags:
            - "*.*.*"

jobs:
    deploy:
        name: Deploy Image
        runs-on: ubuntu-latest
        env:
            IMAGE: ${{ vars.NCR_REGISTRY }}/we-meet
        steps:
            - uses: actions/checkout@v3

            - name: Get current timestamp
              id: timestamp
              run: echo "timestamp=$(date '+%s')" >> "$GITHUB_OUTPUT"

            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ vars.NCR_REGISTRY }}
                username: ${{ secrets.NCR_ACCESS_KEY_ID }}
                password: ${{ secrets.NCR_SECRET_KEY }}

            - name: Deploy development image
              if: startsWith(github.ref, 'refs/heads')
              run: docker push "${{ env.IMAGE }}:${{ steps.timestamp.outputs.timestamp }}"

            - name: Deploy production image
              if: startsWith(github.ref, 'refs/tags')
              run: docker push "${{ env.IMAGE }}:${{ steps.version.outputs.VERSION }}"