name: CD

on:
    push:
        branches:
            - 'master'

env:
    IMAGE: ${{ vars.NCR_REGISTRY }}/we-meet
    IMAGE_TAG: ${{ vars.NCR_REGISTRY }}/we-meet:latest

jobs:
    deploy:
        name: Deploy Image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: ${{ vars.NCR_REGISTRY }}
                username: ${{ secrets.NCR_ACCESS_KEY_ID }}
                password: ${{ secrets.NCR_SECRET_KEY }}

            - name: Deploy image
              run: docker push <span class="math-inline">\{\{ env\.IMAGE \}\}\:</span>{{ env.IMAGE_TAG }}