name: CD

on:
  push:
    branches:
      - 'develop'
    tags:
      - "*.*.*"

env:
  IMAGE: ${{ secrets.NCR_REGISTRY }}/we-meet
  IMAGE_TAG: ${{ secrets.NCR_REGISTRY }}/we-meet:latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to NCR
        uses: docker/login-action@v1 
        with:
          registry: ${{ vars.NCR_REGISTRY }}
          username: ${{ secrets.NCR_ACCESS_KEY_ID }}
          password: ${{ secrets.NCR_SECRET_KEY }}

      # Get current timestamp for tagging image on normal commit in branch develop.
      - name : Get current timestamp 
        id : timestamp 
        if : startsWith(github.ref, 'refs/heads')
        run : echo "TIMESTAMP=$(date '+%s')" >> "$GITHUB_ENV"

       # Get version for tagging image on new release tag.
      - name : Get version 
        id : version 
        if : startsWith(github.ref, 'refs/tags')
        run : echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"

       # Build and push Docker image on normal commit in branch develop.
      - name : Build and push Docker image (commit)
        if : startsWith(github.ref, 'refs/heads')
        uses : docker/build-push-action@v2
        with :
            context ./
            tags "${{ env.IMAGE }}:${{ env.TIMESTAMP }}"
            push true 

       # Build and push Docker image on new release tag.
      - name : Build and push Docker image (tag)
        if : startsWith(github.ref, 'refs/tags')
        uses : docker/build-push-action@v2
        with :
              context ./
              tags "${{ env.IMAGE }}:${{ env.VERSION }}"
              push true 

