name: CD using ArgoCD

on:
  release:
      types: [published]

env:
  IMAGE: ${{ vars.NCR_REGISTRY }}/we-meet
  IMAGE_TAG: ${{ vars.NCR_REGISTRY }}/we-meet:${{ github.run_number }}

jobs:
  deploy:
    name: deploy the new version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Helm repository
        uses: actions/checkout@v3
        with:
          repository: likelion-backend-6th/wemeet_app
          ref: develop
          token: ${{ secrets.PAT }}
      
      - name: Update manifest and push to repository
        run: |
          # replace the image tag in Chart.yaml (apiVersion)
          sed -ie 's/appVersion: ".*"/appVersion: "'${{ github.event.release.tag_name }}'"/g' meet/meet-helm-chart/Chart.yaml
      
          # commit user
          git config --local user.name 'Git Actions[bot]'
          git config --local user.email 'csy5501@gmail.com'
          git commit -a -m "new version tag & num : ${{ github.run_number }}"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: likelion-backend-6th/wemeet_app
          branch: develop