name: CI

on:
    pull_request:
    push:
        branches:
            - 'develop'
        tags:
            - "*.*.*"

env:
    IMAGE: lion-cr01.kr.ncr.ntruss.com/we-meet
    IMAGE_TAG: "${{ IMAGE }}:latest"
    
jobs:
    lint:
        name: Check lint (black)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.11'

            - name: install black
              run: pip install black

            - name: check black
              run: black --check .

    build:
        name: Build Image
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: test
              run: |
                docker-compose -f docker-compose-test.yml up --build -d
                docker-compose -f docker-compose-test.yml run web python manage.py test

            - name: Set up Docker buildx
              uses: docker/setup-buildx-action@v2
            - name: Login to NCR
              uses: docker/login-action@v2
              with:
                registry: lion-cr01.kr.ncr.ntruss.com
                username: ${{ secrets.NCR_ACCESS_KEY_ID }}
                password: ${{ secrets.NCR_SECRET_KEY }}

            - name: Build image
              run: docker buildx build -t "${{ IMAGE }}:${{ IMAGE_TAG }}" --push .

            - name: Push image
              run: docker push "${{ IMAGE }}:${{ IMAGE_TAG }}"